### ISSUE TITLE
Use GitHub Pages instead of htmlpreview.github.io

### ISSUE THREAD

**Issue by qgustavor** [mdipierro/stupid.css#1]
Instead of using other page to load it is better to use GitHub Pages directly (by creating a gh-pages branch and putting HTML there) because it allows more control of the page and better page loading.
Because the htmlpreview page is already shared in some websites consider also redirecting users to the updated URL (a script in the `<head>` can do that).

**Comment by mdipierro** [comment]
I will absolutely do this asap. Thank you.

**Comment by mdipierro** [comment]
should be done. Thanks!
