### ISSUE TITLE
[random theme] Image split on wide screen

### ISSUE THREAD

**Issue by gitoni** [mdipierro/stupid.css#5]
Hi, 

the random themes really look great!!

Except one issue:
I usually browse with wide screens ( ~ 1350 or 1920). 
So the images are always split in two pieces:

https://raw.githubusercontent.com/gitoni/stupid.css/master/randomtheme1.jpg
https://raw.githubusercontent.com/gitoni/stupid.css/master/randomtheme2.jpg
https://raw.githubusercontent.com/gitoni/stupid.css/master/randomtheme3.jpg
https://raw.githubusercontent.com/gitoni/stupid.css/master/randomtheme4.jpg

Browser: Firefox 44.0.2
OS: Windows 10

(Edit: I could not attach the .jpg screenshots files to this issue, so I just uploaded it to my stupid.css fork...)

**Comment by mdipierro** [comment]
should now be fixed. Can you check? thanks for the feedback

**Comment by gitoni** [comment]
Yes, it works great now! Thanks!
