### ISSUE TITLE
Mouse wheel scrolling not smooth, very small increments

### ISSUE THREAD

**Issue by amerikan** [mdipierro/stupid.css#8]
I've noticed that scrolling with my mouse wheel is not smooth and scrolls in small increments, meaning if I spin the wheel a lot it only moves down very little. Using my track pad is fine though. Tested on my Mac OSX El Captian with Firefox 44. 

I tested both http://mdipierro.github.io/stupid.css/index.html and http://www.web2py.com/.

**Comment by mdipierro** [comment]
Interesting. Are you sure this is a stupid.css specific problem? Do other pages scroll fine for you? Do themes have the same problem?Sorry I do not have a wheel to try this at this time.

**Comment by amerikan** [comment]
@mdipierro tested all pages on http://www.web2py.com and they have same issue. All other sites I've visited are fine such as Github.com.

I tested this one http://mdipierro.github.io/stupid.css/widgets/index.html and http://mdipierro.github.io/stupid.css/themes/random.html, those are OK.

**Comment by amerikan** [comment]
Tested on Safari and Chrome, those are ok. So it's just firefox... Not sure what's on the pages causing that.

**Comment by mdipierro** [comment]
I think I know. It is not stupid.css. Those examples contain this JS:

<script>
      // prevent annoying Android horizontal scrolling
      window.addEventListener("scroll", function(){window.scroll(0, window.pageYOffset);}, false);
</script>

I will remove it.

Massimo

**Comment by amerikan** [comment]
Tested http://mdipierro.github.io/stupid.css/index.html after this commit https://github.com/mdipierro/stupid.css/commit/a8e3395f495bd564ba1ded846991a72132aea156. Scrolls good now. Still present on web2py.com though. Closing this issue.

**Comment by mdipierro** [comment]
Thanks for reporting this.

**Comment by amerikan** [comment]
@mdipierro btw where is the repo for http://www.web2py.com web site? I found the following button issue in Mac/Firefox, but don't know where to report it.

![screen shot 2016-03-25 at 11 02 52 am](https://cloud.githubusercontent.com/assets/179356/14050441/22da6bee-f279-11e5-9810-14a858776fcb.png)

**Comment by mdipierro** [comment]
Thank i updated to the latest stupid.css and fixed it.
